namespace :morning do
  desc "Turn off the goddamn alarm"
  task :turn_off_alarm do
    puts "Turning off alarm..."
  end

  desc "Make myself a fancy man"
  task :groom_self do
    puts "Brushing Teeth..."
    puts "Shaving..."
    puts "Showering..."
    puts "Slugging Whiskey..."
  end

  desc "Sweet giver of life and consciousness"
  task :make_coffee do
    cups = ENV['COFFEE'] || 2
    puts "Making #{ cups } cups of coffee..."
  end

  desc "God I hate that stupid little dog"
  task :walk_dog do
    puts "Walking horrible little dog..."
  end

  desc "Get ready for another miserable day"
  task :get_ready => [:turn_off_alarm, :groom_self, :make_coffee, :walk_dog] do
    puts "Oh God, ready for the day"
  end
end

task :default => 'morning:get_ready'

namespace :morning do 
  task :groom_self do 
    puts 'Brushing beard...'
  end
end

namespace :afternoon do 
  desc 'Make more coffee'
  task :make_coffee do 
    Rake::Task['morning:make_coffee'].invoke
    puts 'Adding some rum ...'
    puts 'Ready for the afternoon...'
  end
end

