# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c6544aa76bed8f1310770af6d8248d10c08b88bf8698f8fde06b9aad9776741bb01f535c4b5d016dab121cde0004a068e7bd57fa1a3a17358c43eae92dd4da4

test:
  secret_key_base: d6bf034da82e156ffec28e7aa7d579d413243bd0d8474f2cefe97349eb7bac89c7a29e2d210b778cd3796b030fb4df5f6e6b7348e6a555469df6bcdc4d37d83e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
